// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller"
application.register("autohide", AutohideController)

import ButtonColorController from "./button_color_controller"
application.register("button-color", ButtonColorController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import DateFieldsCommandeController from "./date_fields_commande_controller"
application.register("date-fields-commande", DateFieldsCommandeController)

import DateFieldsController from "./date_fields_controller"
application.register("date-fields", DateFieldsController)

import FormArticleController from "./form_article_controller"
application.register("form-article", FormArticleController)

import FormElementController from "./form_element_controller"
application.register("form-element", FormElementController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PlaceholderCardController from "./placeholder_card_controller"
application.register("placeholder-card", PlaceholderCardController)

import QrCodeAjoutArticleController from "./qr_code_ajout_article_controller"
application.register("qr-code-ajout-article", QrCodeAjoutArticleController)

import QrCodeController from "./qr_code_controller"
application.register("qr-code", QrCodeController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import ReservationFormController from "./reservation_form_controller"
application.register("reservation-form", ReservationFormController)

import StickyTextController from "./sticky_text_controller"
application.register("sticky-text", StickyTextController)

import HomeScrollController from "./home_scroll_controller"
application.register("home-scroll", HomeScrollController)

import CalendarPickerController from "./calendar_picker_controller"
application.register("calendar-picker", CalendarPickerController)